/**
 * GENERATED FILE — do not edit by hand.
 *
 *   node scripts/scrape-reseller.mjs      # refresh facts from the reseller
 *   node scripts/generate-catalog.mjs     # rebuild this file
 *
 * Facts (names, prices, copy, ingredients, imagery) come from the live
 * Coloursbay listing, captured 2026-07-25.
 * Taxonomy (category, line, size, variant grouping, slugs) comes from
 * scripts/curation.mjs — the reseller's own categories are not usable.
 *
 * IMAGERY: imported from the reseller as a working placeholder set. Ownership
 * is unconfirmed — see public/products/README.md before launch.
 *
 * PRICES: the reseller's selling prices, not confirmed as Efe's own RRP.
 * See docs/OPEN-QUESTIONS.md #1 — do not switch on checkout against these.
 *
 * 42 SKUs · 41 on the consumer shelf · 27 buying decisions
 * after variant grouping (11 size families).
 */

import type { Product } from "./catalog";

export const PRODUCTS: Product[] = [
  {
    slug: "african-black-soap-bath-bar",
    name: "African Black Soap Bath Bar",
    category: "black-soap",
    line: "flagship",
    priceMinor: 1500,
    compareAtMinor: 2500,
    sizeG: 200,
    blurb: "Traditional Black Soap Bath Bar 200g.",
    ingredients: "African Black Soap",
    howToUse: "To Bath",
    tags: ["black soap", "bath bar", "traditional", "200g"],
    inStock: true,
    images: ["/products/african-black-soap-bar/1.png"],
  },
  {
    slug: "honey-goat-milk-black-soap-bath-1l",
    name: "Honey & Goat Milk African Black Soap Bath 1Ltr",
    category: "black-soap",
    line: "flagship",
    priceMinor: 13800,
    compareAtMinor: 16050,
    sizeMl: 1000,
    blurb: "African Black Soap Gel Bath 1 Liter enriched with Pure honey and goat milk.",
    ingredients: "African Black Soap Crumble, Pure Honey, Goat Milk Powder",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "honey", "goat milk", "1 liter", "African"],
    inStock: true,
    images: ["/products/honey-goat-milk-2-1l/1.png"],
  },
  {
    slug: "african-black-soap-crumble-250kg",
    name: "Pure African Black Soap Crumble 250kgs",
    category: "black-soap",
    line: "flagship",
    wholesale: true,
    priceMinor: 1375000,
    compareAtMinor: 1625000,
    sizeG: 250000,
    blurb: "Authentic African Black Soap Crumble made with Shea Butter and Cocoa Butter",
    ingredients: "Palm Kennel Oil, Water, Cocoa Pod Ash Distillate, Shea Butter, Cocoa Butter",
    howToUse: "Use as desired by formulators, wholesalers and retailers",
    tags: ["black soap", "crumble", "250kgs", "african", "pure", "Authentic"],
    inStock: true,
    images: ["/products/pure-african-black-soap-crumble-250kgs/1.jpg", "/products/pure-african-black-soap-crumble-250kgs/2.jpg", "/products/pure-african-black-soap-crumble-250kgs/3.png"],
  },
  {
    slug: "blossoms-black-soap-bath-350ml",
    name: "Blossoms African Black Soap Bath 350ml",
    baseName: "Blossoms African Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "blossoms-black-soap-bath",
    priceMinor: 4000,
    compareAtMinor: 4800,
    sizeMl: 350,
    blurb: "African Black Soap Gel Bath 350ml with floral blossom scent.",
    ingredients: "African Black Soap Crumble",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "blossom", "350ml", "African"],
    inStock: true,
    images: ["/products/blossom-350ml/1.png"],
  },
  {
    slug: "blossoms-black-soap-bath-1l",
    name: "Blossoms African Black Soap Bath 1Ltr.",
    baseName: "Blossoms African Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "blossoms-black-soap-bath",
    priceMinor: 11500,
    compareAtMinor: 13800,
    sizeMl: 1000,
    blurb: "African Black Soap Gel Bath 1 Liter with floral blossom scent.",
    ingredients: "African Black Soap Crumble",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "blossom", "1 liter", "African"],
    inStock: true,
    images: ["/products/blossom-2-1l/1.jpg"],
  },
  {
    slug: "cool-herbal-black-soap-bath-350ml",
    name: "Cool Herbal Black Soap Bath 350ml",
    baseName: "Cool Herbal Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "cool-herbal-black-soap-bath",
    priceMinor: 5000,
    compareAtMinor: 6000,
    sizeMl: 350,
    blurb: "African Black Soap Bath Gel 350ml infused with Menthol and Papaya Leaves. A cooling herbal blend.",
    ingredients: "African Black Soap Crumble, Menthol, Papaya Leaves",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "herbal", "350ml", "African"],
    inStock: true,
    images: ["/products/cool-herbal-350ml/1.png"],
  },
  {
    slug: "cool-herbal-black-soap-bath-1l",
    name: "Cool Herbal Black Soap Bath 1ltr.",
    baseName: "Cool Herbal Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "cool-herbal-black-soap-bath",
    priceMinor: 13800,
    compareAtMinor: 16560,
    sizeMl: 1000,
    blurb: "African Black Soap Bath Gel infused with Menthol and Papaya leaves. A cooling herbal blend.",
    ingredients: "African Black Soap Crumble, Papaya Leaves, Menthol",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "herbal", "1 liter", "african"],
    inStock: true,
    images: ["/products/cool-herbal-2-1l/1.jpeg", "/products/cool-herbal-2-1l/2.jpeg", "/products/cool-herbal-2-1l/3.jpeg"],
  },
  {
    slug: "lemon-blast-black-soap-bath-350ml",
    name: "Lemon Blast Black Soap Bath Gel 350ml",
    baseName: "Lemon Blast Black Soap Bath Gel",
    category: "black-soap",
    line: "flagship",
    group: "lemon-blast-black-soap-bath",
    priceMinor: 4000,
    compareAtMinor: 5000,
    sizeMl: 350,
    blurb: "African Black Soap Gel Bath with Orange Peels, a refreshing lemon scent and menthol for that fresh bath every time.",
    ingredients: "African Black Soap, Orange Peels Powder, Menthol",
    tags: ["black soap", "bath gel", "lemon", "350ml"],
    inStock: true,
    images: ["/products/lemon-blast-gel-350ml/1.png"],
  },
  {
    slug: "lemon-blast-black-soap-bath-500ml",
    name: "Lemon Blast Black Soap Bath 500ml",
    baseName: "Lemon Blast Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "lemon-blast-black-soap-bath",
    priceMinor: 6000,
    compareAtMinor: 7200,
    sizeMl: 500,
    blurb: "African Black Soap Bath Gel with Orange Peels, Menthol and a Nice Citrus Scent for that fresh bath always.",
    ingredients: "African Black Soap Crumble, Water, Orange Peels, Menthol, Fragrance",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturise.",
    tags: ["black soap", "bath gel", "lemon", "500ml", "African"],
    inStock: true,
    images: ["/products/lemon-blast-3-500ml/1.png"],
  },
  {
    slug: "lemon-blast-black-soap-bath-1l",
    name: "Lemon Blast African Black Soap Bath 1ltr.",
    baseName: "Lemon Blast African Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "lemon-blast-black-soap-bath",
    priceMinor: 11500,
    compareAtMinor: 13800,
    sizeMl: 1000,
    blurb: "African Black Soap Gel Bath with a refreshing lemon scent and Menthol.",
    ingredients: "African Black Soap, Water, Menthol, Citrus Peels",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "lemon", "1 liter", "African"],
    inStock: true,
    images: ["/products/lemon-blast-2-1l/1.png"],
  },
  {
    slug: "organic-gentle-glow-black-soap-bath-350ml",
    name: "Organic Gentle Glow 350ml",
    baseName: "Organic Gentle Glow",
    category: "black-soap",
    line: "flagship",
    group: "organic-gentle-glow-black-soap-bath",
    priceMinor: 6000,
    compareAtMinor: 7200,
    sizeMl: 350,
    blurb: "African Black Soap Gel Bath 350ml for a gentle, natural glow.",
    tags: ["black soap", "bath gel", "glow", "organic", "350ml"],
    inStock: true,
    images: ["/products/organic-gentle-glow-350ml/1.png", "/products/organic-gentle-glow-350ml/2.png"],
  },
  {
    slug: "organic-gentle-glow-black-soap-bath-1l",
    name: "Organic Gentle Glow Black Soap Bath 1L",
    baseName: "Organic Gentle Glow Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "organic-gentle-glow-black-soap-bath",
    priceMinor: 15000,
    compareAtMinor: 17200,
    sizeMl: 1000,
    blurb: "African Black Soap Bath Gel for a gentle, natural glow.",
    ingredients: "African Black Soap Crumble, Turmeric Powder, Brown Licorice Root Powder, Coffee Powder, Orange Peel Powder, Neem Powder, Kojic Dip.",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "glow", "organic", "1 liter", "African"],
    inStock: true,
    images: ["/products/organic-gentle-glow-1l/1.png", "/products/organic-gentle-glow-1l/2.jpeg", "/products/organic-gentle-glow-1l/3.png"],
  },
  {
    slug: "sweet-lavender-black-soap-bath-350ml",
    name: "Sweet Lavender African Black Soap Bath 350ml",
    baseName: "Sweet Lavender African Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "sweet-lavender-black-soap-bath",
    priceMinor: 4000,
    compareAtMinor: 6000,
    sizeMl: 350,
    blurb: "African Black Soap Gel Bath 350ml with Soothing Lavender Buds and Lavender fragrance.",
    ingredients: "African Black Soap, Water, Lavender Buds",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "lavender", "350ml", "African"],
    inStock: true,
    images: ["/products/sweet-lavender-350ml/1.png"],
  },
  {
    slug: "sweet-lavender-black-soap-bath-1l",
    name: "Sweet Lavender African Black Soap Bath 1Ltr.",
    baseName: "Sweet Lavender African Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "sweet-lavender-black-soap-bath",
    priceMinor: 11500,
    compareAtMinor: 13800,
    sizeMl: 1000,
    blurb: "African Black Soap Bath 1 Liter with Soothing Buds and lavender fragrance.",
    ingredients: "African Black Soap, Water, Lavender Buds, Lavender",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "lavender", "1 liter"],
    inStock: true,
    images: ["/products/sweet-lavender-2-1l/1.jpeg"],
  },
  {
    slug: "tropical-sunrise-black-soap-bath-350ml",
    name: "Tropical Sunrise Black Soap Bath 350ml",
    baseName: "Tropical Sunrise Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "tropical-sunrise-black-soap-bath",
    priceMinor: 4000,
    compareAtMinor: 4800,
    sizeMl: 350,
    blurb: "African Black Soap Gel Bath 350ml with tropical fruity scent.",
    ingredients: "African Black Soap Crumble",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "tropical", "350ml"],
    inStock: true,
    images: ["/products/tropical-sunrise-350ml/1.jpg", "/products/tropical-sunrise-350ml/2.png"],
  },
  {
    slug: "tropical-sunrise-black-soap-bath-1l",
    name: "Tropical Sunrise African Black Soap Bath 1 Ltr",
    baseName: "Tropical Sunrise African Black Soap Bath",
    category: "black-soap",
    line: "flagship",
    group: "tropical-sunrise-black-soap-bath",
    priceMinor: 11500,
    compareAtMinor: 13800,
    sizeMl: 1000,
    blurb: "African Black Soap Gel Bath 1 Liter with tropical fruity scent.",
    ingredients: "African Black Soap Crumble,",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "tropical", "1 liter", "African"],
    inStock: true,
    images: ["/products/tropical-sunrise-2-1l/1.jpeg", "/products/tropical-sunrise-2-1l/2.png"],
  },
  {
    slug: "green-herbal-hair-food-250g",
    name: "Green Herbal Hair Food 250g",
    category: "hair-care",
    line: "supporting",
    priceMinor: 5000,
    compareAtMinor: 6000,
    sizeG: 250,
    blurb: "Hair pomade for all hair types 250g. Nourishes and promotes hair growth.",
    ingredients: "Shea Butter, Cocoa Butter, Coconut Oil, Avocado Oil, Beeswax, Vitamin E Oil",
    howToUse: "Apply to hair and style as desired",
    tags: ["pomade", "hair food", "herbal", "250g", "African"],
    inStock: true,
    images: ["/products/green-herbal-hair-food/1.png"],
  },
  {
    slug: "green-herbal-rice-water-spray-500ml",
    name: "Green Herbal Rice Water Hair Spray 500ml",
    category: "hair-care",
    line: "supporting",
    priceMinor: 5000,
    compareAtMinor: 6000,
    sizeMl: 500,
    blurb: "Hair Repair & Strengthening Spray 500ml with rice water.",
    tags: ["hair spray", "rice water", "repair", "500ml"],
    inStock: true,
    images: ["/products/green-herbal-rice-water-spray/1.jpg", "/products/green-herbal-rice-water-spray/2.jpg"],
  },
  {
    slug: "green-herbal-wash-out-conditioner-500ml",
    name: "Green Herbal Wash Out Conditioner 500ml",
    category: "hair-care",
    line: "supporting",
    priceMinor: 5000,
    compareAtMinor: 6000,
    sizeMl: 500,
    blurb: "Hair Wash Out Conditioner for Natural Hair 500ml. Detangles and softens.",
    tags: ["conditioner", "wash out", "natural hair", "500ml"],
    inStock: true,
    images: ["/products/green-herbal-wash-out-conditioner/1.jpeg", "/products/green-herbal-wash-out-conditioner/2.jpeg"],
  },
  {
    slug: "green-herbal-twist-curl-custard-250g",
    name: "Green Herbal Twist & Curl Custard 250g",
    category: "hair-care",
    line: "supporting",
    priceMinor: 6000,
    compareAtMinor: 7200,
    sizeG: 250,
    blurb: "Hair Twist & Curls Custard 250g. Defines curls and twists with moisture.",
    ingredients: "Shea Butter, Flaxseed Gel, Coconut Oil",
    howToUse: "Use for braids, twists and braid outs",
    tags: ["curl custard", "twist", "natural hair", "250g"],
    inStock: true,
    images: ["/products/green-herbal-twist-curl-custard/1.jpeg"],
  },
  {
    slug: "green-herbal-leave-in-conditioner-500ml",
    name: "Green Herbal Leave-In Conditioner 500ml",
    category: "hair-care",
    line: "supporting",
    priceMinor: 7000,
    compareAtMinor: 8400,
    sizeMl: 500,
    blurb: "Hair Leave-In Conditioner 500ml. Moisturizes and defines natural hair.",
    ingredients: "Aloe Vera Juice, Cactus, Shea Butter, Coconut Oil",
    howToUse: "Use a desired amount on clean washed hair",
    tags: ["conditioner", "leave-in", "natural hair", "500ml", "african"],
    inStock: true,
    images: ["/products/green-herbal-leave-in-conditioner/1.png", "/products/green-herbal-leave-in-conditioner/2.png"],
  },
  {
    slug: "green-herbal-deep-conditioning-cream-500g",
    name: "Green Herbal Deep Conditioning Cream 500g",
    category: "hair-care",
    line: "supporting",
    priceMinor: 10000,
    compareAtMinor: 13000,
    sizeG: 500,
    blurb: "Fenugreek & Aloe Vera Deep Conditioner 500g. Intensive moisture treatment.",
    tags: ["deep conditioner", "fenugreek", "aloe vera", "500g"],
    inStock: true,
    images: ["/products/green-herbal-deep-conditioner/1.png"],
  },
  {
    slug: "anti-dandruff-shampoo-350ml",
    name: "Anti-Dandruff Shampoo 350ml",
    baseName: "Anti-Dandruff Shampoo",
    category: "hair-care",
    line: "supporting",
    group: "anti-dandruff-shampoo",
    priceMinor: 6500,
    compareAtMinor: 7800,
    sizeMl: 350,
    blurb: "African Black Soap Anti-Dandruff Hair Shampoo with Avocado Pit & Papaya Leaves 350ml.",
    ingredients: "African Black Soap, Avocado Seed, Papaya Leaves, Menthol,",
    howToUse: "Use on wet hair. Rinse and continue with wash out conditioner.",
    tags: ["shampoo", "anti-dandruff", "avocado", "papaya", "350ml"],
    inStock: true,
    images: ["/products/anti-dandruff-shampoo-350ml/1.png", "/products/anti-dandruff-shampoo-350ml/2.png"],
  },
  {
    slug: "anti-dandruff-shampoo-500ml",
    name: "Anti-Dandruff Shampoo 500ml",
    baseName: "Anti-Dandruff Shampoo",
    category: "hair-care",
    line: "supporting",
    group: "anti-dandruff-shampoo",
    priceMinor: 8000,
    compareAtMinor: 9600,
    sizeMl: 500,
    blurb: "African Black Soap Anti-Dandruff Hair Shampoo with Avocado Pit & Papaya Leaves 500ml.",
    ingredients: "African Black Soap Crumble, Avocado Seeds, Papaya Leaves, Cloves, Rosemary, Menthol",
    howToUse: "Use once a week on wet hair. Rinse and condition hair.",
    tags: ["shampoo", "anti-dandruff", "avocado", "papaya", "500ml", "African"],
    inStock: true,
    images: ["/products/anti-dandruff-shampoo-500ml/1.png", "/products/anti-dandruff-shampoo-500ml/2.png"],
  },
  {
    slug: "anti-dandruff-shampoo-1l",
    name: "Black Soap Anti-Dandruff Shampoo 1L",
    baseName: "Black Soap Anti-Dandruff Shampoo",
    category: "hair-care",
    line: "supporting",
    group: "anti-dandruff-shampoo",
    priceMinor: 15000,
    compareAtMinor: 18000,
    sizeMl: 1000,
    blurb: "African Black Soap Anti-Dandruff Hair Shampoo with Avocado Pit & Papaya Leaves 1 Liter.",
    ingredients: "African Black Soap, Avocado Seeds, Papaya Leaves, Cloves, Rosemary, Menthol",
    howToUse: "Use once a week on wet hair. Rinse and condition.",
    tags: ["shampoo", "anti-dandruff", "avocado", "papaya", "1 liter", "African"],
    inStock: true,
    images: ["/products/anti-dandruff-shampoo-1l/1.png", "/products/anti-dandruff-shampoo-1l/2.png"],
  },
  {
    slug: "herbal-hair-shampoo-350ml",
    name: "Herbal Hair Shampoo 350ml",
    baseName: "Herbal Hair Shampoo",
    category: "hair-care",
    line: "flagship",
    group: "herbal-hair-shampoo",
    priceMinor: 5000,
    compareAtMinor: 6500,
    sizeMl: 350,
    blurb: "African Black Soap Hair Shampoo infused with herbal extracts for all natural hair types.",
    ingredients: "African Black Soap Crumble, Rosemary, Hibiscus, Papaya Leaves, Moringa Leaves, Bay Leaves, Cloves",
    howToUse: "Rinse your hair with water and pour a generous amount of shampoo to wash. Wash at least twice as the first wash might not lather as is removes build up dirt. Rinse and follow with Efe Wash out Conditioner.",
    tags: ["shampoo", "herbal", "hair care", "350ml", "african", "natural hair"],
    inStock: true,
    images: ["/products/herbal-hair-shampoo-350ml/1.png", "/products/herbal-hair-shampoo-350ml/2.png"],
  },
  {
    slug: "herbal-hair-shampoo-500ml",
    name: "Herbal Hair Shampoo 500ml",
    baseName: "Herbal Hair Shampoo",
    category: "hair-care",
    line: "flagship",
    group: "herbal-hair-shampoo",
    priceMinor: 7000,
    compareAtMinor: 8400,
    sizeMl: 500,
    blurb: "African Black Soap Gel Hair Shampoo 500ml with herbal extracts.",
    ingredients: "African Black Soap Crumble, Cloves, Rosemary, Bay Leafe, Hibiscus,",
    howToUse: "Use to shampoo hair on a wet hair. Recommended to be used at least two times",
    tags: ["shampoo", "herbal", "hair care", "500ml", "African"],
    inStock: true,
    images: ["/products/herbal-hair-shampoo-500ml/1.jpeg", "/products/herbal-hair-shampoo-500ml/2.jpg"],
  },
  {
    slug: "herbal-hair-shampoo-1l",
    name: "African Black Soap Herbal Hair Shampoo 1L",
    baseName: "African Black Soap Herbal Hair Shampoo",
    category: "hair-care",
    line: "flagship",
    group: "herbal-hair-shampoo",
    priceMinor: 13800,
    compareAtMinor: 16560,
    sizeMl: 1000,
    blurb: "African Black Soap Gel Hair Shampoo 1 Liter with herbal extracts for Natural Hair.",
    ingredients: "African Black Soap Crumble, Cloves, Bay Leaves, Rosemary, Hibiscus, Papaya leaves,",
    howToUse: "Pour a desired amount on wet hair and shampoo. Wash twice",
    tags: ["shampoo", "herbal", "hair care", "1 liter", "African"],
    inStock: true,
    images: ["/products/herbal-hair-shampoo-1l/1.png", "/products/herbal-hair-shampoo-1l/2.png"],
  },
  {
    slug: "unscented-hair-body-gel-1l",
    name: "Unscented Hair & Body Gel 1L",
    category: "body-care",
    line: "supporting",
    priceMinor: 11500,
    compareAtMinor: 13800,
    sizeMl: 1000,
    blurb: "African Black Soap Gel Bath 1 Liter — fragrance free.",
    ingredients: "African Black Soap Crumble",
    howToUse: "Use for Bath or Hair Wash",
    tags: ["black soap", "bath gel", "unscented", "1 liter", "African"],
    inStock: true,
    images: ["/products/unscented-2-1l/1.jpeg"],
  },
  {
    slug: "gentle-aloe-milk-350ml",
    name: "Gentle Aloe Milk 350ml",
    baseName: "Gentle Aloe Milk",
    category: "body-care",
    line: "supporting",
    group: "gentle-aloe-milk",
    priceMinor: 5000,
    compareAtMinor: 6000,
    sizeMl: 350,
    blurb: "African Black Soap Bath Gel infused with Aloe Vera and Goat Milk for the ultimate gentle cleansing. Made specially for our children, 12 months and above and adults with sensitive skin. Includes fragrance",
    ingredients: "African Black Soap Crumble, Water, Aloe Vera Juice, Goat Milk",
    howToUse: "Pour a desired amount into your palms or sponge bath. Rub to lather and massage gently on the skin. Rinse and moisturise.",
    tags: ["black soap", "bath gel", "aloe vera", "milk", "350ml", "African"],
    inStock: true,
    images: ["/products/gentle-aloe-milk-350ml/1.png"],
  },
  {
    slug: "gentle-aloe-milk-1l",
    name: "Gentle Aloe Milk 1L",
    baseName: "Gentle Aloe Milk",
    category: "body-care",
    line: "supporting",
    group: "gentle-aloe-milk",
    priceMinor: 13800,
    compareAtMinor: 16560,
    sizeMl: 1000,
    blurb: "African Black Soap Bath Gel infused with Aloe Vera and Goat Milk. suitable for the whole family including children 12 months and above.",
    ingredients: "African Black Soap, Water, Aloe Vera Juice, Goat Milk. Contains fragrance",
    howToUse: "Pour a desired amount into your palms or sponge and rub together to lather. Massage gently on skin, rinse off and moisturise.",
    tags: ["black soap", "bath gel", "aloe vera", "1 liter", "African"],
    inStock: true,
    images: ["/products/gentle-aloe-milk-1l/1.png"],
  },
  {
    slug: "soothing-lavender-milk-350ml",
    name: "Soothing Lavender Milk 350ml",
    baseName: "Soothing Lavender Milk",
    category: "body-care",
    line: "supporting",
    group: "soothing-lavender-milk",
    priceMinor: 5000,
    compareAtMinor: 6000,
    sizeMl: 350,
    blurb: "African Black Soap Gel Bath with lavender and Goat Milk for sensitive skin and Babies.",
    ingredients: "African Black Soap, Lavender Buds, Goat Milk Powder",
    howToUse: "Pour a generous amount in your palm or bath sponge. Rub to lather and massage gently on skin. Rinse off and moisturise.",
    tags: ["black soap", "bath gel", "lavender", "milk", "350ml"],
    inStock: true,
    images: ["/products/soothing-lavender-milk-350ml/1.png"],
  },
  {
    slug: "soothing-lavender-milk-1l",
    name: "Soothing Lavender Milk 1L",
    baseName: "Soothing Lavender Milk",
    category: "body-care",
    line: "supporting",
    group: "soothing-lavender-milk",
    priceMinor: 13800,
    compareAtMinor: 16560,
    sizeMl: 1000,
    blurb: "African Black Soap Bath Gel with Lavender Buds and Goat Milk for Babies and adults with sensitive skin.",
    ingredients: "African Black Soap Crumble, Lavender Buds, Goat Milk Powder",
    howToUse: "Pour a generous portion in your palms or bath sponge, rub together to lather and gently massage it on your body. Rinse and moisturise.",
    tags: ["black soap", "bath gel", "lavender", "milk", "1 liter"],
    inStock: true,
    images: ["/products/soothing-lavender-milk-1l/1.png"],
  },
  {
    slug: "pure-african-shea-butter-250g",
    name: "Pure African Shea Butter",
    category: "lotions-butters",
    line: "supporting",
    priceMinor: 4000,
    compareAtMinor: 6000,
    sizeG: 250,
    blurb: "100% Pure Unrefined Shea Butter 250g. The original African moisturizer.",
    ingredients: "Pure Shea Butter",
    howToUse: "Use as desired.\nTake a preferred amount in your palms and rub together. Massage gently on the skin or hair ensuring full coverage. Use Day and Night.",
    tags: ["shea butter", "pure", "unrefined", "250g", "African"],
    inStock: true,
    images: ["/products/pure-shea-butter-250g/1.png"],
  },
  {
    slug: "efes-organic-body-butter",
    name: "Efe's Organic Body Butter",
    category: "lotions-butters",
    line: "supporting",
    priceMinor: 7000,
    compareAtMinor: 8400,
    blurb: "Moisturizing Body Butter with Shea Butter, Cocoa Butter, Coconut Oil & Bees Wax 250g.",
    ingredients: "Shea Butter, Cocoa Butter, Coconut Oil, Avocado Oil, Beeswax, Tea Tree, Lavender & Frankincense Essential Oils, Vitamin E Oil, Niacinamide. Contains Fragrance",
    howToUse: "Take a preferred amount in your palms and rub together. Massage gently on the skin ensuring full coverage. Use Day and Night.",
    tags: ["body butter", "shea butter", "cocoa butter", "250g", "African"],
    inStock: true,
    images: ["/products/organic-body-butter/1.png"],
  },
  {
    slug: "shea-avoco-body-lotion",
    name: "Shea Avoco Body Lotion",
    category: "lotions-butters",
    line: "supporting",
    priceMinor: 7000,
    compareAtMinor: 8400,
    blurb: "Body Lotion with Shea Butter, Avocado Oil & Coconut Oil 380ml.",
    ingredients: "Shea Butter, Avocado Oil, Coconut Oil, Tea Tree Oil, Lavender Essential Oil, Frankincense Oil, Vitamin E oil, Fragrance",
    howToUse: "Squeeze your preffered quantity in your palms and rub together. Apply to the skin massaging gently to ensure full coverage. Use Day and Night",
    tags: ["body lotion", "shea butter", "avocado", "coconut oil", "380ml", "African"],
    inStock: true,
    images: ["/products/shea-avoco-body-lotion/1.png"],
  },
  {
    slug: "rose-roselle-glow-lotion",
    name: "Rose Roselle Glow Lotion",
    category: "lotions-butters",
    line: "supporting",
    priceMinor: 10000,
    compareAtMinor: 12000,
    blurb: "This Body Lotion combines the deeply hydrating and soothing benefits of Rose and the Natural Alpha-Hydroxy Acids (AHAs) and Vitamin C of Roselle to gently brighten your skin. Together, they promote a radiant, soft and even-toned appearance.",
    ingredients: "Aqua, Rose, Roselle, Shea Butter, Coconut Oil, Avocado Oil, Rose Oil, Lavender, Tea Tree & Frankincense Essential Oils",
    howToUse: "Take a preferred amount in your palms and rub together. Massage gently on the skin ensuring full coverage. Use Day and Night.",
    tags: ["Rose", "Roselle", "Body Lotion", "Body Glow", "African"],
    inStock: true,
    images: ["/products/rose-roselle-glow-lotion/1.png", "/products/rose-roselle-glow-lotion/2.png"],
  },
  {
    slug: "carrot-aloe-glow-butter",
    name: "Carrot & Aloe Glow Butter",
    category: "lotions-butters",
    line: "supporting",
    priceMinor: 11000,
    compareAtMinor: 13200,
    blurb: "Glow Butter with Carrot and Aloe Vera 250g. Brightens and nourishes.",
    ingredients: "Carrot Juice, Aloe Vera Juice, Shea Butter, Cocoa Butter, Coconut Oil, Avocado Oil, Carrot Oil, Beeswax, Tea Tree, Lavender & Frankincense Essential Oils, Kojic Dip, Vitamin E Oil, Allantoin, Niacinamide. Contains Fragrance",
    howToUse: "Take a preferred amount in your palms and rub together. Massage gently on the skin ensuring full coverage. Use Day and Night.",
    tags: ["glow butter", "carrot", "aloe vera", "250g", "shea butter", "African"],
    inStock: true,
    images: ["/products/carrot-aloe-glow-butter/1.png"],
  },
  {
    slug: "acne-blemish-cleanser-350ml",
    name: "Acne & Blemish Cleanser 350ml",
    baseName: "Acne & Blemish Cleanser",
    category: "skincare",
    line: "supporting",
    group: "acne-blemish-cleanser",
    priceMinor: 5000,
    compareAtMinor: 6500,
    sizeMl: 350,
    blurb: "African Black Soap Gel Bath 350ml specially formulated to fight acne and blemishes.",
    ingredients: "African Black Soap Crumble, Neem Leaves, Turmeric Powder, Coffee Grinds, Sandalwood Powder, Moringa Powder, Papaya Powder.",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "acne", "blemish", "350ml", "african"],
    inStock: true,
    images: ["/products/acne-blemish-cleanser-350ml/1.png", "/products/acne-blemish-cleanser-350ml/2.png"],
  },
  {
    slug: "acne-blemish-cleanser-1l",
    name: "Acne & Blemish Cleanser 1L",
    baseName: "Acne & Blemish Cleanser",
    category: "skincare",
    line: "supporting",
    group: "acne-blemish-cleanser",
    priceMinor: 13800,
    compareAtMinor: 16050,
    sizeMl: 1000,
    blurb: "African Black Soap Gel Bath 1 Liter for acne and blemish control.",
    ingredients: "African Black Soap Crumble, Neem Powder, Moringa Powder, Papaya leaves, Turmeric, Orange Peels",
    howToUse: "Pour a desired amount into your palms or bath sponge and rub to lather. Apply to your skin and massage gently ensuring a thorough cleansing. Rinse off and moisturize.",
    tags: ["black soap", "bath gel", "acne", "1 liter", "african"],
    inStock: true,
    images: ["/products/acne-blemish-cleanser-1l/1.png", "/products/acne-blemish-cleanser-1l/2.jpeg", "/products/acne-blemish-cleanser-1l/3.png"],
  },
  {
    slug: "carrot-face-body-oil-100ml",
    name: "Carrot Face & Body Oil 100ml",
    category: "oils",
    line: "supporting",
    priceMinor: 5000,
    compareAtMinor: 6000,
    sizeMl: 100,
    blurb: "Carrot Oil 100ml. Rich in Vitamin A & E for repair and moisturizing face and body.",
    ingredients: "Carrot Oil, Rosehip Oil, Grapeseed Oil, Lavender, Tea Tree, Frankincense, Vitamin E",
    howToUse: "Use three drops and massage gently on the face. Use as much as needed on the body",
    tags: ["carrot oil", "face oil", "body oil", "vitamin a", "100ml", "African"],
    inStock: true,
    images: ["/products/carrot-face-body-oil-100ml/1.png"],
  },
  {
    slug: "green-herbal-hair-scalp-oil-120ml",
    name: "Green Herbal Hair & Scalp Oil 120ml",
    category: "oils",
    line: "supporting",
    priceMinor: 6000,
    compareAtMinor: 7200,
    sizeMl: 120,
    blurb: "Hair Growth & Repair Oil 120ml. Stimulates scalp and promotes hair growth.",
    ingredients: "Sunflower Oil, Coconut Oil, Talinum, lavender, Tea Tree, Vitamin E, Peppermint",
    howToUse: "Use on the scalp and massage into the hair.",
    tags: ["hair oil", "scalp oil", "hair growth", "120ml", "miracle", "African"],
    inStock: true,
    images: ["/products/green-herbal-scalp-oil-120ml/1.png", "/products/green-herbal-scalp-oil-120ml/2.jpeg", "/products/green-herbal-scalp-oil-120ml/3.png"],
  },
];
